config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :tasks
  root to: 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks

  def incomplete_tasks
    tasks.where(completed_at: nil)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project, touch: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes!(params[:project])
    redirect_to projects_url, notice: "Project was successfully updated."
  end

  def destroy
    Project.destroy(params[:id])
    redirect_to projects_url, notice: "Project was successfully destroyed."
  end

  private
  def project_params
    params.require(:product).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(task_params)
    redirect_to projects_url, notice: "Task was successfully updated."
  end

  private 
  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CacheExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/projects/_project.html.erb
<% cache project do %>
<h2>
  <%= link_to project.name, edit_project_path(project) %>
</h2>
<ul> <%= render project.tasks %> </ul>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= render @projects %>

app/views/tasks/_task.html.erb
<li>
  <%= task.name %>
  <%= link_to "edit", edit_task_path(task) %>
</li>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for @task do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>